### ISSUE TITLE
there is a serious issue down here

### ISSUE THREAD

**Issue by antonl-dev** [Aridlvory/college-works#17]
Awwww hell naw. Bruh what happened to you nicka?
You sorry as hell, down bad? Getting no girls in mech?

I)   Starring is own repository (god damn )
II)  Opening pull request in his on project (hell naw)
III) Anddd merging them himself (absolute abdomination)
(Total destruction)

You are beyond the point of shame nicka
This is badd man

Hope you get well soon
Best regards
-bloomingchad

**Comment by Aridlvory** [comment]
lol sorry i didnt see your issue
was busy lately

yea this is a serious issue because i am just trying to fill git with my homeworks demn 😂

**Comment by Aridlvory** [comment]
just give me a contact or smthn brh

**Comment by Aridlvory** [comment]
i aint gonna close this until i have that
